controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /pruebas
    controller: App\Controller\DefaultController::index

index1:
    path: /uno
    controller: App\Controller\DefaultController::index1

index2:
    path: /dos
    controller: App\Controller\DefaultController::index2

imagenes:
    path: /
    controller: App\Controller\ProyectoController::index