### GET de una imagen
GET http://sym.local/api/imagenesapi/13
Content-Type: application/json

### Petición GET
GET http://sym.local/api/prueba
Content-Type: application/json

### GET para obtener todas las imágenes del contacto logueado
GET http://sym.local/api/imagenesapi
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NzIxODQ1ODIsImV4cCI6MTc3MjE4ODE4Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.JfBRIod4-WixZQ6E1OEWtEOoU3OqhquEtIMFNyFkedMqrmtCcFiekmQdNzjsAHrVJW1RDNwLw5_VcYW0qIkTNKwgsJg6ZNejCsoPqx48sS2tH-zkw6enF0c6tCAmlYXhcCqJnBxLge201-0bT-n8EM5YMFZkv2eyFs0Cglh1-N1wPHMkROvBkutsSByonQpGWHBaxjo_c8y7swCTcZPtkRFCyHAezXWzI5vdHydmY49mr0As013pcMruDDI5968_cUZO_fuyP7Obfq9qwoL103rL0Q319GnfCwpoLBdymDxjFVqOHY6z9Jkl_Fn3ZOYaJoZ7wYvMNNlU6HJgVnR_9A

### GET para obtener todos los datos ordenados
GET http://sym.local/api/imagenesapi/ordenadas/descripcion
Content-Type: application/json

### GET para obtener datos filtrados
GET http://sym.local/api/imagenesapi/ordenadas/id?fechaInicial=2024-01-03&descripcion=imag
Content-Type: application/json

### DELETE de una imagen
DELETE http://sym.local/api/imagenesapi/13
Content-Type: application/json

### Send POST request with json body
POST http://sym.local/api/imagenesapinueva
Content-Type: application/json

{
 "nombre": "dawpunch.png",
 "descripcion": "esta es la imagen post 1",
 "numVisualizaciones": "21",
 "numLikes": "12",
 "numDownloads": "4",
 "categoria": "2",
 "usuario": "1",
 "fecha": "20/01/2024"
}

### Send POST request with json body
POST http://sym.local/api/auth/register
Content-Type: application/json

{
 "username": "user4",
 "password": "user4",
 "email": "carlosrodrigobeltra1@gmail.com"
}

### PUT de actualización de una imagen
PUT http://sym.local/api/imagenesapi/14
Content-Type: application/json

{
 "nombre": "imagen post 8 actualizado",
 "descripcion": "esta es la imagen post 8 actualizado",
 "numVisualizaciones": "11",
 "numLikes": "22",
 "numDownloads": "33",
 "categoria": "1",
 "fecha": "02/02/2024",
 "usuario": "1"
}

### 1. POST - Login (Obtener el Token JWT)
POST http://sym.local/api/auth/login_check
Content-Type: application/json

{
    "username": "admin",
    "password": "a"
}

### 2. POST - Probar una ruta protegida
POST http://sym.local/api/imagenesapinueva
Content-Type: application/json
Authorization: Bearer ***

{
 "nombre": "dawpunch.png",
 "descripcion": "esta es la imagen post 2",
 "numVisualizaciones": "1",
 "numLikes": "2",
 "numDownloads": "3",
 "categoria": "2",
 "fecha": "02/02/2023"
}

### GET para obtener una imagen del contacto logueado
GET http://sym.local/api/imagenesapi/14
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NzIxODQ1ODIsImV4cCI6MTc3MjE4ODE4Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.JfBRIod4-WixZQ6E1OEWtEOoU3OqhquEtIMFNyFkedMqrmtCcFiekmQdNzjsAHrVJW1RDNwLw5_VcYW0qIkTNKwgsJg6ZNejCsoPqx48sS2tH-zkw6enF0c6tCAmlYXhcCqJnBxLge201-0bT-n8EM5YMFZkv2eyFs0Cglh1-N1wPHMkROvBkutsSByonQpGWHBaxjo_c8y7swCTcZPtkRFCyHAezXWzI5vdHydmY49mr0As013pcMruDDI5968_cUZO_fuyP7Obfq9qwoL103rL0Q319GnfCwpoLBdymDxjFVqOHY6z9Jkl_Fn3ZOYaJoZ7wYvMNNlU6HJgVnR_9A

### GET para obtener los datos de un usuario logueado
GET http://sym.local/api/profile
Content-Type: application/json
Authorization: Bearer ***